"
Поведение кешированных тегов

Public API and Key Messages

- message one   
- message two 
- (for bonus points) how to create instances.

   One simple example is simply gorgeous.
 
Internal Representation and Key Implementation Points.

    Instance Variables
	alluuid:		<Object>


    Implementation Points
"
Class {
	#name : #ACacheTags,
	#superclass : #ATags,
	#instVars : [
		'alluuid',
		'printVersion'
	],
	#category : #'Accounting-Core'
}
